import * as common from './common';
import * as config from './config';
import * as evaluate from './evaluate';
import * as fetch from './fetch';
import * as instantiate from './instantiate';
import * as resolve from './resolve';
import * as systemjsLoader from './systemjs-loader';
import * as systemjsProductionLoader from './systemjs-production-loader';
declare const _default: {
    common: typeof common;
    config: typeof config;
    evaluate: typeof evaluate;
    fetch: typeof fetch;
    'format-helpers': any;
    instantiate: typeof instantiate;
    resolve: typeof resolve;
    'system-production': any;
    system: systemjsLoader.default;
    'systemjs-loader': typeof systemjsLoader;
    'systemjs-production-loader': typeof systemjsProductionLoader;
};
export default _default;
